### ISSUE TITLE
JWTs and security

### ISSUE THREAD

**Issue by QuinnBast** [Subterfuge-Revived/Remake-Backend#1]
JWTs are encoded session tokens that let you send all information about a user that would be relevant while still being secure. Here's a link to a php JWT framework. THis lets you send encoded user information like the user's email, username, user id, etc.

[Here is a php JWT framework](https://github.com/web-token/jwt-framework)

Will need to be cautious of session hi-jacking and other security concerns. Will need to also consider security methods to ensure tokens cannot be stolen: "i.e. use http-only cookies to protect against XSS, use TLS to protect against sniffing, use CSRF tokens or other techniques to protect against CSRF etc. And you might include some information in the protected token which make misuse harder, like a fingerprint of the browser, source IP of the user etc" [source](https://security.stackexchange.com/questions/170599/what-protects-a-jwt-from-being-hijacked-and-used-to-pose-as-the-original-user)

Note: This may no longer be valid since we are now using laravel.

**Comment by griendt** [comment]
XSS and CSRF are attacks relevant for a webpage-based service (i.e. a website accessed through a browser). Laravel does support protection against these out-of-the-box (all forms have a CSRF token embedded). But they make no sense in a purely API-based context. For that we are using our session tokens. (And of course the current Laravel backend supports having both a browser context and the JSON API context.)

We should of course use HTTPS/TLS to prevent interception of session tokens and for that we need a certificate. There are ways to get one though, [Let's Encrypt](https://letsencrypt.org/) being a well known free provider of SSL certificates. We can only set that up once we have a domain name though.

**Comment by QuinnBast** [comment]
Yes, we will definitely use HTTPS/TLS. I will close this issue since CSRF seems to not be an issue.
