### ISSUE TITLE
Clean up stale and no longer relevant branches

### ISSUE THREAD

**Issue by griendt** [Subterfuge-Revived/Remake-Backend#22]
There are some branches that used the old architecture style with bare PHP files. We should check these branches for features or logic that is not yet implemented in the current `dev` branch. If such featuers are lacking, we should create issues for those. Either way, these old branches cannot be merged anymore and so they should be deleted.

**Comment by QuinnBast** [comment]
I deleted the inactive branches. I reviewed their functionality and most features were already implemented in the laravel branch.
